apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
  externalIPs:
    - 192.168.0.104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: grimreapermortis/webserver:1.0.0
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
