nScreenWidth: 255
nScreenHeight: 255
nPixel: 4
sMenuConfig: assets/Menu.json
sMenuAnimated: assets/AnimatedSprite.json
sMenuSprite: assets/Sprite-0002.png
sMenuSpriteScale: 1
nMapSize: 6
nMapLoadRange: 2
sNoise:
  nSize: 100
  fStep: 0.2
vLightSource: { x: 10, y: 30, z: 0 }
vCamera: { x: 0, y: 50, z: 0 }
nCameraStep: 8
nMouseSpeed: 0.5
MenuSprites:
  MENU: [8, 2]
