apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-deployment
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template
  template:
    metadata:
      labels:
        app: template
    spec:
      containers:
        - name: template
          image: grimreapermortis/webserver:1.0.10
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
