apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: template
spec:
  selector:
    app: webserver
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
  externalIPs:
    - 192.168.0.104
