apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  namespace: psql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/var/lib/postgresql/11/main/"
    server: 192.168.0.105
