apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
  namespace: psql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sd1/psql"