apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
  namespace: psql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 10Gi
